core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('message/',views.MessageView.as_view(), name='message'),
    path('projects/<int:pk>/', views.Portfolio.as_view(), name='portfolio'),
    path('payments/', views.SendMoney.as_view(), name="send-money"),
    path('payments/transaction/<str:pk>/', views.PayConfrim.as_view(), name="pay-confirm"),
]

ogulu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    mediaurl = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += mediaurl

core/models.py
from django.db import models
import uuid
import datetime
import logging
from pypaystack import Transaction as PSTransaction
from django.conf import settings

logger = logging.getLogger(__name__)

# Create your models here.

class Site(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField()
    favicon = models.ImageField()
    appleicon = models.ImageField()

    def __str__(self) -> str:
        return self.name

    def has_one_or_more_instance(self): # TODO: create a mixin that allows a model to have only one instance 
        return Site.objects.all().count() > 1

    def save(self, *args, **kwargs):
        if self.has_one_or_more_instance():
            logger.info('`Site` already has an instance.')
            return
        super().save(*args, **kwargs)


class MyInformation(models.Model):
    OPTIONS = (
        ('olevel','Olevel'),
        ('undergrad','Undegraduate'),
        ('beng','B.Eng'),
        ('bsc','B.Sc'),
        ('meng','Master'),
        ('phd','PHD')
    )
    site = models.OneToOneField(Site, related_name='my_info', on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100, help_text='Your name')
    lastname = models.CharField(max_length=100, help_text='Your surname')
    nickname = models.CharField(max_length=50)
    display_text = models.TextField(max_length=200, help_text='What text should appear on your site\'s landing page', default="The <span>top</span> feels so much better than the bottom.")
    dob = models.DateField('Date of birth')
    age = models.PositiveIntegerField(blank=True, help_text="leave empty. it is automatically generated")
    bio = models.TextField(help_text='Some information about you')
    occupation = models.CharField(max_length=50, help_text="what you do for a living")
    quote = models.TextField(help_text='your favourite quote')
    background_image = models.ImageField(help_text="The image that appears at the background of your site", blank=True)
    about_image = models.ImageField(help_text="The image that appears at the about", blank=True)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=20, help_text="Where you're based at the moment")
    degree = models.CharField(max_length=15, choices=OPTIONS)


    def get_age(self):
        """
        Returns age based on the `dob` supplied
        """
        age = datetime.date.today() - self.dob
        return age.days / 365
    
    def is_birthday(self):
        """
        Returns boolean value of if it's `MyInfomation`
        instance birthday based on the `self.dob`
        """
        today = datetime.date.today()
        return (today.day == self.dob.day) and (today.month == self.dob.month)
    
    def has_one_or_more_instance(self): # TODO: create a mixin that allows a model to have only one instance 
        return MyInformation.objects.all().count() > 1

    def save(self, *args, **kwargs):
        if self.has_one_or_more_instance():
            logger.info('`MyInformation` already has an instance.')
            return
        self.age = self.get_age()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.firstname} {self.lastname}"

class Interest(models.Model):
    info = models.ForeignKey(MyInformation, related_name='interests', on_delete=models.CASCADE)
    interest = models.CharField(max_length=100, help_text="things that you're attracted to")

    def __str__(self):
        return self.interest

class Service(models.Model):
    info = models.ForeignKey(MyInformation, related_name='services', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, help_text="name of the service you're providing")
    description = models.CharField(max_length=100, help_text="brief info of what the service is about")

    def __str__(self):
        return self.name

class Skill(models.Model):
    info = models.ForeignKey(MyInformation, related_name='skills', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, help_text="the name of the skill")
    proficiency = models.PositiveIntegerField(help_text="how good you are at doing it in percentage(Note: Do not include `%`)")

    def __str__(self):
        return self.name

class Testimonial(models.Model):
    """
    Model stores what clients are saying about `MyInformation` instance
    """
    info = models.ForeignKey(MyInformation, related_name='testimonials', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    occupation = models.CharField(max_length=50)
    testimony = models.TextField()

    def __str__(self):
        return self.name

class PhoneNumber(models.Model):
    info = models.ForeignKey(MyInformation, related_name='phone_numbers', on_delete=models.CASCADE)
    number = models.CharField(max_length=15)

    def __str__(self):
        return self.number

class Email(models.Model):
    info = models.ForeignKey(MyInformation, related_name='emails', on_delete=models.CASCADE)
    email = models.EmailField()

    def __str__(self):
        return self.email

class SocialAccount(models.Model):
    OPTIONS = (
        ('facebook','Facebook'),
        ('instagram','Instagram'),
        ('twitter','Twitter'),
        ('tiktok','Tik Tok'),
        ('telegram','Telegram'),
    )
    info = models.ForeignKey(MyInformation, related_name='social_accounts', on_delete=models.CASCADE)
    name = models.CharField(max_length=15, choices=OPTIONS)
    link = models.URLField()

    def __str__(self):
        return self.get_name_display()


class BirthdayWish(models.Model):
    info = models.ForeignKey(MyInformation, related_name='wishes', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    relationship = models.CharField(max_length=50)
    message = models.TextField()

    def __str__(self):
        return self.name


class Resume(models.Model):
    info = models.OneToOneField(MyInformation, related_name='resume', on_delete=models.CASCADE)

    def __str__(self):
        return self.info.firstname

class Summary(models.Model):
    """
    Model hold the resume summary
    """
    resume = models.OneToOneField(Resume, on_delete=models.CASCADE, related_name='summary')
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    resume_summary = models.TextField()
    address = models.TextField(max_length=50)
    phone_number = models.CharField(max_length=14)
    email = models.EmailField()

    def get_fullname(self):
        return f"{self.firstname} {self.lastname}"

    def __str__(self):
        return self.get_fullname()


class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='educations')
    degree_acquired = models.CharField(max_length=30)
    duration = models.CharField(max_length=15, help_text="e.g 2019-2021")
    institution = models.CharField(max_length=30)
    brief_info = models.TextField(help_text="A brief summary of what the education acquired entailed")
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
    
    def __str__(self):
        return self.degree_acquired

class ProfessionalExperience(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name='experiences')
    job_title = models.CharField(max_length=30)
    duration = models.CharField(max_length=15, help_text="e.g 2019-2021")
    location = models.CharField(max_length=50)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
    
    def __str__(self):
        return self.job_title

class Highlight(models.Model):
    """
    Stores highlights of personal experiences
    """
    experience = models.ForeignKey(ProfessionalExperience, on_delete=models.CASCADE, related_name='highlights')
    highlight = models.CharField(max_length=200)

    def __str__(self):
        return self.highlight


class Message(models.Model):
    """
    Stores messages sent to `MyInformation` instance
    """
    info = models.ForeignKey(MyInformation, related_name='messages', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class PictureCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "picture categories"

    def __str__(self):
        return self.name

class ProjectCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "project categories"

    def __str__(self):
        return self.name

class Project(models.Model):
    OPTIONS = (
        ('completed','Completed'),
        ('in_progress','In Progress')
    )
    info = models.ForeignKey(MyInformation, related_name='projects', on_delete=models.CASCADE)
    categories = models.ManyToManyField(ProjectCategory)
    name = models.CharField(max_length = 100)
    client = models.CharField(max_length=50)
    client_logo = models.ImageField(blank=True)
    date = models.DateField()
    status = models.CharField(max_length=15, choices=OPTIONS, default=OPTIONS[1][0])
    url = models.URLField(blank=True)
    description =models.TextField()

    def __str__(self):
        return self.name
    
class ProjectImage(models.Model):
    project = models.ForeignKey(Project, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField()

    def __str__(self):
        return self.project.name


class MyImage(models.Model):
    info = models.ForeignKey(MyInformation, related_name='pictures', on_delete=models.CASCADE)

core/forms.py
from django import forms
from django.db.models import fields
from . import models

class BirthdayWishForm(forms.ModelForm):
    class Meta:
        model = models.BirthdayWish
        fields = '__all__'

class MessageForm(forms.ModelForm):
    class Meta:
        model = models.Message
        fields = '__all__'

class TransactionFrom(forms.ModelForm):
    class Meta:
        model = models.Transaction
        fields = [
            'name',
            'email',
            'amount',
        ]

core/views.py
import logging
from django.shortcuts import redirect
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponse
from django.contrib import messages
from django.views.generic import TemplateView, DetailView
from typing import Dict, Any
from django.views.generic.edit import FormView
from . import forms, models
# Create your views here.

logger = logging.getLogger(__name__)


class Index(FormView):
    template_name = 'core/index.html'
    form_class = forms.BirthdayWishForm
    form_name  = 'wish_form'


    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['picture_categories'] = models.PictureCategory.objects.all()
        context['project_categories'] = models.ProjectCategory.objects.all()
        
        try:
            context['wish_form'] = self.wish_form
        except:
            context['wish_form'] = self.prepopulate_wish_form()
        return context

    def prepopulate_wish_form(self):
        initial = {
            'info': models.MyInformation.objects.all().first()
        }
        return forms.BirthdayWishForm(initial=initial)

    def form_valid(self, form):
        messages.success(self.request, "Your message was successfully sent.")
        form.save()
        return redirect('core:index')

    def form_invalid(self, form):
        messages.error(self.request, "An error occured.")
        self.wish_form = form
        return self.get(self.request)


class MessageView(FormView):
    form_class = forms.MessageForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Message successfully sent!")
        return redirect('core:index')
    
    def form_invalid(self, form):
        messages.success(self.request, f"An error occured!<br>{form.errors}<br>Try again.")
        return redirect('core:index')


class SendMoney(FormView):
    form_class = forms.TransactionFrom
    template_name = 'core/send-money.html'

    def form_valid(self, form: forms.TransactionFrom) -> HttpResponse:
        transaction = form.save()
        messages.success(self.request, "New Transaction created!")
        return redirect(reverse('core:pay-confirm', kwargs={"pk": transaction.pk}))

    def form_invalid(self, form: forms.TransactionFrom) -> HttpResponse:
        messages.error(self.request, "Unabel to created new transaction")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['send_money'] = True
        return context


class PayConfrim(DetailView):

    template_name = 'core/send-money.html'
    context_object_name = 'transaction'
    model = models.Transaction


    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        transaction = models.Transaction.objects.get(pk=self.kwargs['pk'])
        transaction.verify_payment()
        context = super().get_context_data(**kwargs)
        context['context'] = transaction
        context['pay_confirm'] = True
        context['paystack_public_key'] = settings.PAYSTACK_PUBLIC_KEY
        return context

def bounce(request, pk):
    return redirect(reverse('core:pay-confrim', kwargs={'pk': pk}))


class Portfolio(DetailView):
    template_name = 'core/portfolio-details.html'
    model = models.Project

core/templates/core/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %}{% endblock %}</title>
    <meta content="{% block meta_description %}{% endblock %}" name="description">
    <meta content="{% block meta_keywords %}{% endblock %}" name="keywords">

    <!-- Favicons -->
    <link href="{% if site.favicon %}{{ site.favicon.url }}{% else %}{% static 'core/img/favicon.png' %}{% endif %}" rel="icon">
    <link href="{% if site.appleicon %}{{ site.appleicon.url }}{% else %}{% static 'core/img/apple-touch-icon.png' %}{% endif %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet">
    <style>
        body::before {
            content: "";
            position: fixed;
            background: #040404 url("{% if site.my_info.background_image %}{{ site.my_info.background_image.url }}{% else %}{% static 'core/img/illyria-default-lockscreen.jpg' %}{% endif %}") top right no-repeat;
            background-size: cover;
            left: 0;
            right: 0;
            top: 0;
            height: 100vh;
            z-index: -1;
        }
    </style>

    <!-- =======================================================
  * Template Name: Personal - v4.6.0
  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
<header id="header">
    <div class="container">

        <h1><a href="{% url 'core:index' %}">{{ site.my_info.firstname }} {{ site.my_info.lastname }}</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a> -->
        <h2>{{ site.my_info.display_text | safe }}</h2>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link active" href="#header">Home</a></li>
                {% if site.my_info.is_birthday %}
                <li><a class="nav-link" href="#birthday">Birthday</a></li>
                {% endif %}
                <li><a class="nav-link" href="#about">About</a></li>
                <li><a class="nav-link" href="#gallery">Gallery</a></li>
                <li><a class="nav-link" href="#resume">Resume</a></li>
                <li><a class="nav-link" href="#services">Services</a></li>
                <li><a class="nav-link" href="#portfolio">Portfolio</a></li>
                <li><a class="nav-link" href="#contactx">Contact</a></li>
                <li><a class="nav-link" href="{% url 'core:send-money' %}">Send money</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        <div class="social-links">
            {% for account in site.my_info.social_accounts.all %}
            <a href="{{ account.link }}" target="_blank" class="{{ account.name }}"><i class="bi bi-{{ account.name }}"></i></a>
            {% endfor %}
        </div>
        

    </div>
</header><!-- End Header -->


    {% block content %}{% endblock %}

    
    <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/personal-free-resume-bootstrap-template/ -->
        Template by <a href="https://bootstrapmade.com/">BootstrapMade</a><br>
        Designed by <a href="https://euphoria-development.herokuapp.com">Gbenga</a>
    </div>

    <!-- Vendor JS Files -->
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'core/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'core/vendor/purecounter/purecounter.js' %}"></script>
    <script src="{% static 'core/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'core/vendor/waypoints/noframework.waypoints.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'core/js/main.js' %}"></script>

    <!-- Notification script -->
    <script src="{% static 'core/js/jquery.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap-notify.js' %}"></script>
    <script type="text/javascript">
        function showNotification(a,e,color,icn,msg){
            color=color,$.notify({icon:icn,message:msg},{type:color,timer:8e3,placement:{from:a,align:e}})}

        $(document).ready(function() {
          {% for message in messages %}
          setTimeout(1000, showNotification(
            'top',
            'left',
            "{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}",
            "now-ui-icons travel_info",
            '{{ message | safe }}'));
            {% endfor %}
        });
      </script>

</body>

</html>

core/templates/core/portfolio-details.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{ project.name }}{% endblock %}

{% block content %}

  <main id="main">

    <!-- ======= Portfolio Details ======= -->
    <div id="portfolio-details" class="portfolio-details">
      <div class="container">

        <nav id="navbar" class="navbar mb-5">
          <ul>
              <li><a class="nav-link active" href="{% url 'core:index' %}#header">Home</a></li>
              {% if site.my_info.is_birthday %}
              <li><a class="nav-link" href="{% url 'core:index' %}#birthday">Birthday</a></li>
              {% endif %}
              <li><a class="nav-link" href="{% url 'core:index' %}#about">About</a></li>
              <li><a class="nav-link" href="{% url 'core:index' %}#resume">Resume</a></li>
              <li><a class="nav-link" href="{% url 'core:index' %}#services">Services</a></li>
              <li><a class="nav-link" href="{% url 'core:index' %}#portfolio">Portfolio</a></li>
              <li><a class="nav-link" href="{% url 'core:index' %}#contactx">Contact</a></li>
              <li><a class="nav-link" href="{% url 'core:send-money' %}">Send money</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        <div class="row">

          <div class="col-lg-8">
            
            <h2 class="portfolio-title">{{ project.name }}</h2>

            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                {% for image in project.images.all %}
                <div class="swiper-slide">
                  <img src="{{ image.image.url }}" alt="{{ project.name }}" class="img-fluid">
                </div>
                {% endfor %}

              </div>
              <div class="swiper-pagination"></div>
            </div>

          </div>

          <div class="col-lg-4 portfolio-info">
            <h3>Project information</h3>
            <ul>
              <li><strong>{% if project.categories.all.count > 1%}Categories{% else %}Category{% endif %}</strong>: {% for category in project.categories.all %}{{ category.name | upper }}, {% endfor %}</li>
              <li><strong>Client</strong>: {{ project.client }}</li>
              <li><strong>Project date</strong>: 01 March, 2020</li>
              {% if project.url %}<li><strong>Project URL</strong>: <a href="{{ project.url }}">{{ project.url }}</a></li>{% endif %}
              <li><strong>Status</strong>: {{ project.get_status_display }}</li>
            </ul>

            <p>
              {{ project.description }}
            </p>
          </div>

        </div>

      </div>
    </div><!-- End Portfolio Details -->

  </main><!-- End #main -->
{% endblock %}

core/templates/core/send-money.html
{% extends 'core/base.html' %}

{% block content %}

<br><br><br>

<div class="container">

    <nav id="navbar" class="navbar mb-5">
        <ul>
            <li><a class="nav-link active" href="{% url 'core:index' %}#header">Home</a></li>
            {% if site.my_info.is_birthday %}
            <li><a class="nav-link" href="{% url 'core:index' %}#birthday">Birthday</a></li>
            {% endif %}
            <li><a class="nav-link" href="{% url 'core:index' %}#about">About</a></li>
            <li><a class="nav-link" href="{% url 'core:index' %}#resume">Resume</a></li>
            <li><a class="nav-link" href="{% url 'core:index' %}#services">Services</a></li>
            <li><a class="nav-link" href="{% url 'core:index' %}#portfolio">Portfolio</a></li>
            <li><a class="nav-link" href="{% url 'core:index' %}#contactx">Contact</a></li>
            <li><a class="nav-link" href="{% url 'core:send-money' %}">Send money</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            {% if send_money %}
            <div class="card" style="width: 20rem;">
                <div class="card-body text-black">
                    <h5 class="card-title">Send Money</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Any amount you send goes a long way.</h6>
                    <form action="{% url 'core:send-money' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <span class="input-group-text">Name</span>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text">Email</span>
                            <input type="text" class="form-control" name="email">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text">₦</span>
                            <input type="text" class="form-control" aria-label="Amount (to the nearest naira)"
                                name="amount">
                            <span class="input-group-text">.00</span>
                        </div>
                        <button type="submit" class="btn btn-success">continue</button>
                    </form>
                </div>
            </div>
            {% endif %}
            {% if pay_confirm %}
            <div class="card" style="width: 20rem;">
                <div class="card-body text-black">
                    {% if transaction.is_verified %}
                    <h5 class="card-title">Payment has been confirmed, may you purse never run dry. Amen.</h5>
                    {% else %}
                    <h5 class="card-title">Confirm & Pay</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Osheyy alert ti fe wole. 😋🤑🤑</h6>
                    <p><b>Name</b> {{ transaction.name }}</p>
                    <p><b>Email</b> {{ transaction.email }}</p>
                    <p><b>Amount</b> ₦{{ transaction.amount }}</p>
                    <button class="btn btn-success" id="payButton">Pay</button>
                    <p style="font-size: smaller; color: red;">Sorry, please refesh this page after payments to verify
                        their success. This won't happen again because we're working on it.</p>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="col-3"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://js.paystack.co/v1/inline.js"></script>

<script>
    const payButton = document.getElementById('payButton');
    payButton.addEventListener("click", payWithPaystack, false);
    function payWithPaystack(e) {
        e.preventDefault();
        let handler = PaystackPop.setup({
            key: "{{ paystack_public_key }}",
            email: "{{ transaction.email }}",
            amount: {{ transaction.amount }} * 100,
                ref: "{{ transaction.transaction_id }}",

                    onClose: function () {
                        console.log('Window closed.');
                    },
    callback: function (response) {
        document.location.reload(true); // true to force reload from server
    }
        });
    handler.openIframe();
    }
</script>
{% endblock %}